RoundLabelButton
giusene/Revolutiorant-AdminPanel pull request #10
Opened 2023-05-15 15:28 UTC by Gianmaph

2023-05-15 17:13 UTC, Luisazizzo requested changes

2023-05-15 17:13 UTC, Luisazizzo commented on ui-kit/RoundLabelButton/styles.module.scss
> +  padding: rem(0px) rem(6px);
Elimina questa riga

2023-05-15 17:13 UTC, Luisazizzo commented on ui-kit/RoundLabelButton/styles.module.scss
> +    padding: rem(8px);
metti: padding: rem(8px) rem(12px);

2023-05-15 17:13 UTC, Luisazizzo commented on ui-kit/RoundLabelButton/styles.module.scss
> +    padding: rem(10px) rem(12px);
metti:  padding: rem(8px) rem(20px);

2023-05-16 10:46 UTC, giusene approved these changes

2023-05-16 10:47 UTC, merged